/**
 * Generates `src/lib/emoji-catalog.ts` — the Twemoji-backed emoji list shown in
 * the picker's Emoji tab.
 *
 * Strategy: join `emojibase-data` (human labels + CLDR tags + canonical order)
 * with the ACTUAL icon list shipped by `@iconify-json/twemoji`, emitting only
 * emojis whose computed `twemoji:<slug>` id exists in that set. That guarantees
 * every catalog tile resolves through `@iconify/react` (no broken glyphs); any
 * straggler that doesn't map is silently dropped.
 *
 * Both source packages are devDependencies only — the committed output ships at
 * runtime, so nothing here runs in the browser. Re-run after bumping either
 * package to refresh for new Unicode releases:
 *
 *   bun run scripts/gen-emoji-catalog.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import twemoji from '@iconify-json/twemoji/icons.json';
import compact from 'emojibase-data/en/compact.json';
import type { EmojiCatalogEntry } from '../src/lib/emoji-catalog-types.ts';

// emojibase group 2 = "Component" (skin-tone + hair-colour modifiers) — not
// standalone insertable emojis, so excluded along with any skin-tone variant.
const COMPONENT_GROUP = 2;

interface CompactEmoji {
  hexcode: string;
  label: string;
  group?: number;
  order?: number;
  tags?: string[];
  emoticon?: string | string[];
}

/** Twemoji slug convention: drop apostrophes, kebab the rest (`twelve o'clock` → `twelve-oclock`). */
function toSlug(label: string): string {
  return label
    .toLowerCase()
    .replace(/['’`]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildKeywords(e: CompactEmoji): string {
  const emoticons = Array.isArray(e.emoticon) ? e.emoticon : e.emoticon ? [e.emoticon] : [];
  const parts = [e.label, ...(e.tags ?? []), ...emoticons];
  const words = new Set<string>();
  for (const part of parts) {
    for (const w of part.toLowerCase().split(/\s+/)) {
      const t = w.trim();
      if (t) words.add(t);
    }
  }
  return [...words].join(' ');
}

const t = twemoji as {
  prefix: string;
  icons: Record<string, unknown>;
  aliases?: Record<string, unknown>;
};
const validSlugs = new Set<string>([...Object.keys(t.icons), ...Object.keys(t.aliases ?? {})]);

const entries: EmojiCatalogEntry[] = [];
let dropped = 0;
for (const raw of compact as CompactEmoji[]) {
  if (raw.group === undefined || raw.group === COMPONENT_GROUP) continue;
  if (/skin tone/i.test(raw.label)) continue;
  const slug = toSlug(raw.label);
  if (!validSlugs.has(slug)) {
    dropped++;
    continue;
  }
  entries.push({ id: `${t.prefix}:${slug}`, label: raw.label, keywords: buildKeywords(raw) });
}

// emojibase compact is already in canonical (group, order) sequence, so array
// order gives the natural Smileys → People → Animals → … scroll.
const header = `// GENERATED by scripts/gen-emoji-catalog.ts — DO NOT EDIT BY HAND.
// Twemoji emoji catalog for the picker's Emoji tab. Regenerate with:
//   bun run scripts/gen-emoji-catalog.ts
import type { EmojiCatalogEntry } from './emoji-catalog-types.ts';

export const EMOJI_CATALOG: EmojiCatalogEntry[] = ${JSON.stringify(entries)};
`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'src', 'lib', 'emoji-catalog.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header);

console.log(`Wrote ${entries.length} emojis to ${outPath} (dropped ${dropped} unmapped).`);
